"""empty message

Revision ID: 17b7ab85904d
Revises: e54071ecb76b
Create Date: 2024-03-26 01:38:47.661773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b7ab85904d'
down_revision = 'e54071ecb76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemuser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('email_address', sa.String(length=500), nullable=True),
    sa.Column('passcode', sa.String(length=500), nullable=True),
    sa.Column('mobile_no', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=1000), nullable=True),
    sa.Column('last_name', sa.String(length=1000), nullable=True),
    sa.Column('email_address', sa.String(length=500), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('home_address', sa.String(length=1000), nullable=True),
    sa.Column('url_of_picture', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['systemuser.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('systemuser')
    # ### end Alembic commands ###
